project:
  type: book
  pre-render: 
  - _pre_render.R
    
book:
  title: "Let's git it started"
  subtitle: "Transparency and reproducibility across the RWE study lifecycle with HARPER, Git and GitHub Copilot"
  author: "Janick Weberpals <br> Shirley V. Wang <br> Anna Schultze <br> John Tazare"
    
    
  chapters:
    - index.qmd # landing page
    - syllabus.qmd
    - 01_protocol.qmd
    - 02_intro.qmd
    - 03_workshop.qmd
    - 04_reporting.qmd

  reader-mode: true
  repo-url: https://github.com/janickweberpals/icpe-git-2025
  repo-actions: [issue]

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
    engine: knitr
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true
    # comments:
    #   hypothesis: true

# bibliography: references.bib
# csl: epidemiology.csl

